import sqlite3
conn = sqlite3.connect('data/cybersrs.db')
cursor = conn.cursor()
cursor.execute('SELECT name FROM sqlite_master WHERE type="table"')
print('Tables:', [row[0] for row in cursor.fetchall()])
cursor.execute('PRAGMA table_info(evaluation_run)')
print('evaluation_run columns:', [row[1] for row in cursor.fetchall()])
cursor.execute('PRAGMA table_info(generation_run)')
print('generation_run columns:', [row[1] for row in cursor.fetchall()])
cursor.execute('PRAGMA table_info(srs_version)')
print('srs_version columns:', [row[1] for row in cursor.fetchall()])