"""Validated request and response schemas for conversational chat."""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


class ChatMessage(BaseModel):
    """One user or assistant message supplied as conversation context."""

    model_config = ConfigDict(extra="forbid")

    role: Literal["user", "assistant"]
    content: str = Field(min_length=1, max_length=8_000)


class ChatCompletionRequest(BaseModel):
    """Request for one validated conversational assistant response."""

    model_config = ConfigDict(extra="forbid")

    messages: list[ChatMessage] = Field(min_length=1, max_length=30)
    project_id: str | None = None
    stream: bool = False


class ChatModelOutput(BaseModel):
    """Structured payload generated by the main LLM before citation enrichment."""

    model_config = ConfigDict(extra="forbid")

    answer: str = Field(min_length=1, max_length=12_000)
    cited_source_ids: list[str] = Field(default_factory=list, max_length=8)


class ChatCitation(BaseModel):
    """A citation verified against a chunk retrieved for the current answer."""

    model_config = ConfigDict(extra="forbid")

    source_id: str
    source_document_id: str
    document_title: str
    chunk_index: int
    page_or_section: str | None = None
    relevance_score: float


class ChatCompletionResponse(BaseModel):
    """Validated response returned to the conversational UI."""

    content: str
    is_project_description: bool = False
    model_name: str
    rag_enabled: bool = False
    citations: list[ChatCitation] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)


IntentType = Literal[
    "general_question",
    "project_description",
    "srs_project_request",
    "srs_modification",
    "srs_generation",
    "clarification",
]


class IntentClassificationRequest(BaseModel):
    """Request for deterministic workflow-intent classification."""

    model_config = ConfigDict(extra="forbid")

    message: str = Field(min_length=1, max_length=8_000)
    project_id: str | None = None
    has_srs: bool = False
    workflow_stage: (
        Literal["welcome", "analyzing", "clarifying", "generating", "ready", "error"] | None
    ) = None


class IntentClassificationResponse(BaseModel):
    """Deterministic workflow intent used by the frontend state machine."""

    intent: IntentType
    confidence: float = Field(ge=0.0, le=1.0)
    extracted_data: dict[str, object] = Field(default_factory=dict)


class SRSEditChatRequest(BaseModel):
    """Natural-language request to update an existing SRS requirement."""

    model_config = ConfigDict(extra="forbid")

    project_id: str
    version_id: str
    instruction: str = Field(min_length=1, max_length=8_000)


class SRSEditChatResponse(BaseModel):
    """Result of applying a validated chat-driven SRS edit."""

    success: bool
    message: str
    updated_srs: dict[str, object] | None = None
