"""Prompt templates for CyberSRS LLM interactions.

All prompts follow the structure:
- SYSTEM: Task-specific instructions + output schema
- USER: User content (sanitised)

Retrieved RAG chunks (when available) are placed in a clearly delimited
section within the USER message (SEC-019).
"""

from .analysis import ANALYSIS_SYSTEM_PROMPT, ANALYSIS_USER_TEMPLATE
from .clarification import CLARIFICATION_SYSTEM_PROMPT, CLARIFICATION_USER_TEMPLATE
from .srs import (
    ACCEPTANCE_TESTING_SYSTEM_PROMPT,
    ACCEPTANCE_TESTING_USER_TEMPLATE,
    ARCHITECTURE_SYSTEM_PROMPT,
    ARCHITECTURE_USER_TEMPLATE,
    DATA_REQUIREMENTS_SYSTEM_PROMPT,
    DATA_REQUIREMENTS_USER_TEMPLATE,
    FUNCTIONAL_REQUIREMENTS_SYSTEM_PROMPT,
    FUNCTIONAL_REQUIREMENTS_USER_TEMPLATE,
    NETWORK_REQUIREMENTS_SYSTEM_PROMPT,
    NETWORK_REQUIREMENTS_USER_TEMPLATE,
    NON_FUNCTIONAL_REQUIREMENTS_SYSTEM_PROMPT,
    NON_FUNCTIONAL_REQUIREMENTS_USER_TEMPLATE,
    RISKS_ASSUMPTIONS_SYSTEM_PROMPT,
    RISKS_ASSUMPTIONS_USER_TEMPLATE,
    SECURITY_REQUIREMENTS_SYSTEM_PROMPT,
    SECURITY_REQUIREMENTS_USER_TEMPLATE,
    SRS_SYSTEM_PROMPT,
    SRS_USER_TEMPLATE,
    THREATS_SYSTEM_PROMPT,
    THREATS_USER_TEMPLATE,
)

__all__ = [
    "ANALYSIS_SYSTEM_PROMPT",
    "ANALYSIS_USER_TEMPLATE",
    "CLARIFICATION_SYSTEM_PROMPT",
    "CLARIFICATION_USER_TEMPLATE",
    "SRS_SYSTEM_PROMPT",
    "SRS_USER_TEMPLATE",
    "FUNCTIONAL_REQUIREMENTS_SYSTEM_PROMPT",
    "FUNCTIONAL_REQUIREMENTS_USER_TEMPLATE",
    "NON_FUNCTIONAL_REQUIREMENTS_SYSTEM_PROMPT",
    "NON_FUNCTIONAL_REQUIREMENTS_USER_TEMPLATE",
    "SECURITY_REQUIREMENTS_SYSTEM_PROMPT",
    "SECURITY_REQUIREMENTS_USER_TEMPLATE",
    "DATA_REQUIREMENTS_SYSTEM_PROMPT",
    "DATA_REQUIREMENTS_USER_TEMPLATE",
    "NETWORK_REQUIREMENTS_SYSTEM_PROMPT",
    "NETWORK_REQUIREMENTS_USER_TEMPLATE",
    "ARCHITECTURE_SYSTEM_PROMPT",
    "ARCHITECTURE_USER_TEMPLATE",
    "THREATS_SYSTEM_PROMPT",
    "THREATS_USER_TEMPLATE",
    "ACCEPTANCE_TESTING_SYSTEM_PROMPT",
    "ACCEPTANCE_TESTING_USER_TEMPLATE",
    "RISKS_ASSUMPTIONS_SYSTEM_PROMPT",
    "RISKS_ASSUMPTIONS_USER_TEMPLATE",
]
